import { connectDB } from "./db";
import { Vehicle } from "@/models/Vehicle";

const vehicles = [
  {
    name: "Toyota Camry",
    type: "sedan",
    description:
      "Comfortable and reliable sedan perfect for city and highway driving.",
    pricePerDay: 150,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
    available: true,
    features: ["Bluetooth", "Backup Camera", "Apple CarPlay", "Cruise Control"],
  },
  {
    name: "Honda CR-V",
    type: "suv",
    description:
      "Spacious SUV with advanced safety features and premium comfort.",
    pricePerDay: 200,
    seats: 7,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    available: true,
    features: ["Sunroof", "Lane Assist", "360 Camera", "Heated Seats"],
  },
  {
    name: "BMW 5 Series",
    type: "luxury",
    description:
      "Premium luxury sedan with cutting-edge technology and performance.",
    pricePerDay: 450,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
    available: true,
    features: [
      "Leather Seats",
      "Harman Kardon Audio",
      "Heads-up Display",
      "Massaging Seats",
    ],
  },
  {
    name: "Hyundai i20",
    type: "hatchback",
    description: "Nimble and fuel-efficient hatchback ideal for city commutes.",
    pricePerDay: 90,
    seats: 5,
    transmission: "manual",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800",
    available: true,
    features: ["Touchscreen", "Rear Sensors", "USB Charging", "ABS"],
  },
  {
    name: "Tesla Model 3",
    type: "sedan",
    description: "All-electric sedan with autopilot and zero emissions.",
    pricePerDay: 350,
    seats: 5,
    transmission: "automatic",
    fuel: "electric",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800",
    available: true,
    features: [
      "Autopilot",
      "Over-the-air Updates",
      '15" Touchscreen',
      "Supercharging",
    ],
  },
  {
    name: "Toyota Fortuner",
    type: "suv",
    description: "Rugged and powerful SUV built for all terrains.",
    pricePerDay: 280,
    seats: 7,
    transmission: "automatic",
    fuel: "diesel",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    available: true,
    features: ["4WD", "Roof Rails", "Tow Hook", "Multi-terrain Select"],
  },
  {
    name: "Audi A6",
    type: "luxury",
    description:
      "Luxury executive sedan with premium comfort and advanced technology.",
    pricePerDay: 420,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800",
    available: true,
    features: [
      "Virtual Cockpit",
      "Leather Seats",
      "Sunroof",
      "Adaptive Cruise",
    ],
  },
  {
    name: "Mercedes-Benz C-Class",
    type: "luxury",
    description:
      "Elegant luxury sedan offering exceptional comfort and performance.",
    pricePerDay: 430,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
    available: true,
    features: [
      "Ambient Lighting",
      "Parking Assist",
      "Premium Audio",
      "Wireless Charging",
    ],
  },
  {
    name: "Kia Seltos",
    type: "suv",
    description: "Stylish compact SUV with modern features and spacious cabin.",
    pricePerDay: 180,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800",
    available: true,
    features: ["Sunroof", "Apple CarPlay", "Ventilated Seats", "Rear Camera"],
  },
  {
    name: "Mahindra XUV700",
    type: "suv",
    description: "Feature-rich SUV with ADAS and premium interiors.",
    pricePerDay: 230,
    seats: 7,
    transmission: "automatic",
    fuel: "diesel",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    available: true,
    features: ["ADAS", "Panoramic Sunroof", "360 Camera", "Alexa Built-in"],
  },
  {
    name: "Maruti Suzuki Swift",
    type: "hatchback",
    description: "Popular hatchback known for fuel efficiency and reliability.",
    pricePerDay: 80,
    seats: 5,
    transmission: "manual",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800",
    available: true,
    features: ["ABS", "Bluetooth", "Touchscreen", "USB Charging"],
  },
  {
    name: "Volkswagen Virtus",
    type: "sedan",
    description: "Premium sedan with refined engine and German engineering.",
    pricePerDay: 170,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1549924231-f129b911e442?w=800",
    available: true,
    features: [
      "Digital Cockpit",
      "Cruise Control",
      "LED Headlights",
      "Wireless Android Auto",
    ],
  },
  {
    name: "Honda City",
    type: "sedan",
    description: "Reliable midsize sedan with spacious interiors.",
    pricePerDay: 160,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800",
    available: true,
    features: ["Sunroof", "Lane Watch Camera", "Cruise Control", "Push Start"],
  },
  {
    name: "Nissan Magnite",
    type: "suv",
    description: "Compact SUV with bold styling and efficient performance.",
    pricePerDay: 140,
    seats: 5,
    transmission: "manual",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800",
    available: true,
    features: ["Rear Camera", "Wireless Charger", "Air Purifier", "LED DRLs"],
  },
  {
    name: "Ford Endeavour",
    type: "suv",
    description: "Premium full-size SUV built for adventure.",
    pricePerDay: 310,
    seats: 7,
    transmission: "automatic",
    fuel: "diesel",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
    available: true,
    features: ["4WD", "Terrain Modes", "Leather Seats", "Panoramic Roof"],
  },
  {
    name: "MG Hector",
    type: "suv",
    description: "Connected SUV packed with smart technology.",
    pricePerDay: 220,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800",
    available: true,
    features: [
      "Voice Commands",
      "Panoramic Sunroof",
      "360 Camera",
      "Connected Car",
    ],
  },
  {
    name: "Jeep Compass",
    type: "suv",
    description: "Adventure-ready SUV with premium styling.",
    pricePerDay: 260,
    seats: 5,
    transmission: "automatic",
    fuel: "diesel",
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800",
    available: true,
    features: ["4x4", "Hill Assist", "Leather Seats", "Navigation"],
  },
  {
    name: "Lexus ES300h",
    type: "luxury",
    description: "Luxury hybrid sedan delivering comfort and efficiency.",
    pricePerDay: 480,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    available: true,
    features: ["Hybrid", "Mark Levinson Audio", "Ventilated Seats", "Sunroof"],
  },
  {
    name: "Range Rover Evoque",
    type: "luxury",
    description: "Luxury compact SUV with iconic styling.",
    pricePerDay: 520,
    seats: 5,
    transmission: "automatic",
    fuel: "diesel",
    image: "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800",
    available: true,
    features: ["AWD", "Meridian Audio", "360 Camera", "Leather Interior"],
  },
  {
    name: "Porsche Macan",
    type: "luxury",
    description: "Sporty luxury SUV with thrilling performance.",
    pricePerDay: 650,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    available: true,
    features: [
      "Sport Mode",
      "BOSE Audio",
      "Panoramic Roof",
      "Adaptive Suspension",
    ],
  },
  {
    name: "Skoda Slavia",
    type: "sedan",
    description: "Premium sedan combining style, safety and comfort.",
    pricePerDay: 175,
    seats: 5,
    transmission: "automatic",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1493238792000-8113da705763?w=800",
    available: true,
    features: ["Cruise Control", "Sunroof", "Wireless Charging", "LED Lamps"],
  },
  {
    name: "Renault Kiger",
    type: "suv",
    description: "Affordable compact SUV ideal for city driving.",
    pricePerDay: 130,
    seats: 5,
    transmission: "manual",
    fuel: "petrol",
    image: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=800",
    available: true,
    features: ["Rear Camera", "Touchscreen", "Steering Controls", "ABS"],
  },
  {
    name: "Tata Nexon EV",
    type: "suv",
    description: "Electric SUV with excellent range and modern features.",
    pricePerDay: 240,
    seats: 5,
    transmission: "automatic",
    fuel: "electric",
    image: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800",
    available: true,
    features: [
      "Fast Charging",
      "Connected Car",
      "Cruise Control",
      "Digital Cluster",
    ],
  },
  {
    name: "BYD Atto 3",
    type: "suv",
    description: "Modern electric SUV with premium technology.",
    pricePerDay: 300,
    seats: 5,
    transmission: "automatic",
    fuel: "electric",
    image: "https://images.unsplash.com/photo-1504215680853-026ed2a45def?w=800",
    available: true,
    features: ["360 Camera", "Rotating Screen", "ADAS", "Fast Charging"],
  },
];

export async function seedVehicles() {
  await connectDB();
  await Vehicle.deleteMany({});
  await Vehicle.insertMany(vehicles);
  console.log("✅ Vehicles seeded successfully");
}
